config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


def trigger_error(request):
    division_by_zero = 1 / 0


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("movies/", include("movies.urls", namespace="movies")),
    path("books/", include("books.urls", namespace="books")),
    path("categories/", include("categories.urls", namespace="categories")),
    path("people/", include("people.urls", namespace="people")),
    path("users/", include("users.urls", namespace="users")),
    path("favs/", include("favs.urls", namespace="favs")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("admin/", admin.site.urls),
    path("sentry-debug/", trigger_error),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from core.views import resolve_home, resolve_search

app_name = "core"

urlpatterns = [
    path("", resolve_home, name="home"),
    path("search/", resolve_search, name="search"),
]

favs/urls.py
from django.urls import path
from favs.views import resolve_add, FavsDetail

app_name = "favs"

urlpatterns = [
    path("", FavsDetail.as_view(), name="favs"),
    path("toggle/<int:pk>/", resolve_add, name="add"),
]

users/urls.py
from django.urls import path
from users.views import (
    logout_view,
    LoginView,
    SignUpView,
    UserProfileView,
    UpdateProfileView,
    UpdatePasswordView,
)

app_name = "users"

urlpatterns = [
    path("logout/", logout_view, name="logout"),
    path("login/", LoginView.as_view(), name="login"),
    path("signup/", SignUpView.as_view(), name="signup"),
    path("<int:pk>/", UserProfileView.as_view(), name="profile"),
    path("update-profile/", UpdateProfileView.as_view(), name="update"),
    path("update-passwod/", UpdatePasswordView.as_view(), name="password"),
]

templates/partials/footer.html
<footer>
  <div class="text-center py-10 border-t font-medium text-gray-500 -mx-40">
      &copy; Nomad Media
  </div>
</footer>

templates/partials/header.html
  <header class="inset-0 container max-w-full flex justify-around bg-blue-400 text-white py-4 fixed h-20 items-center">
    <a class="hover:text-gray-300" href="{% url 'core:home' %}">Home</a>
    <a class="hover:text-gray-300" href="{% url 'core:search' %}">Search</a>
    {% if user.is_authenticated %}
      <a class="hover:text-gray-300" href="{% url 'favs:favs' %}">My Favs</a>
      <a class="hover:text-gray-300" href="{% url 'users:logout' %}">Log Out</a>
      <a class="hover:text-gray-300" href="{% url 'users:profile' user.pk %}">My Profile</a>
    {% else %}
      <a class="hover:text-gray-300" href="{% url 'users:login' %}">Log In</a>
      <a class="hover:text-gray-300" href="{% url 'users:signup' %}">Sign Up</a>
    {% endif %}
  </header>