books/urls.py
from django.urls import path
from books.views import BooksView, BookDetail, CreateBook, UpdateBook

app_name = "books"

urlpatterns = [
    path("", BooksView.as_view(), name="books"),
    path("<int:pk>/", BookDetail.as_view(), name="book"),
    path("<int:pk>/update/", UpdateBook.as_view(), name="update"),
    path("create/", CreateBook.as_view(), name="create"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


def trigger_error(request):
    division_by_zero = 1 / 0


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("movies/", include("movies.urls", namespace="movies")),
    path("books/", include("books.urls", namespace="books")),
    path("categories/", include("categories.urls", namespace="categories")),
    path("people/", include("people.urls", namespace="people")),
    path("users/", include("users.urls", namespace="users")),
    path("favs/", include("favs.urls", namespace="favs")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("admin/", admin.site.urls),
    path("sentry-debug/", trigger_error),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from core.views import resolve_home, resolve_search

app_name = "core"

urlpatterns = [
    path("", resolve_home, name="home"),
    path("search/", resolve_search, name="search"),
]

favs/urls.py
from django.urls import path
from favs.views import resolve_add, FavsDetail

app_name = "favs"

urlpatterns = [
    path("", FavsDetail.as_view(), name="favs"),
    path("toggle/<int:pk>/", resolve_add, name="add"),
]

movies/urls.py
from django.urls import path
from movies.views import MoviesView, MovieDetail, CreateMovie, UpdateMovie

app_name = "movies"

urlpatterns = [
    path("", MoviesView.as_view(), name="movies"),
    path("<int:pk>/", MovieDetail.as_view(), name="movie"),
    path("<int:pk>/update/", UpdateMovie.as_view(), name="update"),
    path("create/", CreateMovie.as_view(), name="create"),
]

people/urls.py
from django.urls import path
from people.views import PeopleView, PersonDetail, CreatePerson, UpdatePerson

app_name = "people"

urlpatterns = [
    path("", PeopleView.as_view(), name="people"),
    path("<int:pk>/", PersonDetail.as_view(), name="person"),
    path("<int:pk>/update/", UpdatePerson.as_view(), name="update"),
    path("create/", CreatePerson.as_view(), name="create"),
]

reviews/urls.py
from django.urls import path
from . import views

app_name = "reviews"

urlpatterns = [
    path("add/<int:pk>/", views.add_review, name="add"),
    path("delete/<int:review_pk>/", views.delete_review, name="delete"),
]

books/models.py
from django.urls import reverse
from django.db import models
from core.models import CoreModel


class Book(CoreModel):

    """ Book Model """

    title = models.CharField(max_length=120)
    year = models.IntegerField()
    cover_image = models.ImageField(upload_to="book_cover_images", blank=True)
    category = models.ForeignKey(
        "categories.Category", on_delete=models.CASCADE, related_name="books"
    )
    writer = models.ForeignKey(
        "people.Person", on_delete=models.CASCADE, related_name="books"
    )

    # field 대신 review의 평균값을 표시하기 위해 함수로 표현
    def rating(self):
        all_reviews = self.reviews.all()
        all_ratings = 0
        if len(all_reviews) > 0:
            for review in all_reviews:
                all_ratings += review.rating

            return round(all_ratings / len(all_reviews), 2)
        return 0

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("books:book", kwargs={"pk": self.pk})

    class Meta:
        ordering = ["-created_at"]

people/models.py
from django.urls import reverse
from django.db import models
from core.models import CoreModel


class Person(CoreModel):

    """ Person Model """

    KIND_ACTOR = "actor"
    KIND_DIRECTOR = "director"
    KIND_WRITER = "writer"

    KIND_CHOICES = (
        (KIND_ACTOR, "Actor"),
        (KIND_DIRECTOR, "Director"),
        (KIND_WRITER, "Writer"),
    )

    name = models.CharField(max_length=120)
    photo = models.ImageField(upload_to="person_images", blank=True)
    kind = models.CharField(max_length=15, choices=KIND_CHOICES)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "People"
        ordering = ["created_at"]

    def get_absolute_url(self):
        return reverse("people:person", kwargs={"pk": self.pk})

books/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.core.paginator import Paginator
from books.models import Book
from users import mixins as user_mixins
from reviews import forms as review_forms
from reviews import models as review_models


class BooksView(ListView):

    model = Book
    paginate_by = 15
    paginate_orphans = 5
    ordering = "-created_at"
    context_object_name = "books"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page_title"] = "All Books"

        paginator = context["paginator"]
        page_numbers_range = 10
        max_index = len(paginator.page_range)
        page = self.request.GET.get("page")
        current_page = int(page) if page else 1

        start_index = int((current_page - 1) / page_numbers_range) * page_numbers_range
        end_index = start_index + page_numbers_range
        if end_index >= max_index:
            end_index = max_index
        page_range = paginator.page_range[start_index:end_index]

        context["page_range"] = page_range
        return context


class BookDetail(DetailView):
    model = Book
    context_object_name = "book"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        review_form = review_forms.CreateReviewForm()
        context["form"] = review_form

        # book의 pk 가져옴
        book_pk = self.kwargs.get("pk")
        page = self.request.GET.get("page")

        # 한페이지당 표시 수랑 페이지 끊는 단위를 같이 쓰고 있음
        # 굳이 같이 쓸필요 없음
        page_numbers_range = 5
        # 가져온 book_pk에 해당하는 review만 가져옴
        review_list = review_models.Review.objects.filter(book__pk=book_pk)
        paginator = Paginator(review_list, page_numbers_range)
        max_index = len(paginator.page_range)
        reviews = paginator.get_page(page)

        # page 끊은 단위 계산
        current_page = int(page) if page else 1
        start_index = int((current_page - 1) / page_numbers_range) * page_numbers_range
        end_index = start_index + page_numbers_range
        if end_index >= max_index:
            end_index = max_index
        page_range = paginator.page_range[start_index:end_index]

        context["page_range"] = page_range
        context["reviews"] = reviews  # paginator  직접 반환
        # print(vars(reviews.paginator)) 안에 뭐 들었는지 확인용.
        return context


class CreateBook(user_mixins.LoggedInOnlyView, CreateView):
    model = Book
    fields = (
        "title",
        "year",
        "cover_image",
        "category",
        "writer",
    )


class UpdateBook(user_mixins.LoggedInOnlyView, UpdateView):
    model = Book
    fields = (
        "title",
        "year",
        "cover_image",
        "category",
        "writer",
    )

people/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from people.models import Person
from movies.models import Movie
from books.models import Book
from users import mixins as user_mixins


class PeopleView(ListView):

    model = Person
    paginate_by = 15
    paginate_orphans = 5
    ordering = "-created_at"
    context_object_name = "people"
    template_name = "people/people_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page_title"] = "All People"

        paginator = context["paginator"]
        page_numbers_range = 10
        max_index = len(paginator.page_range)
        page = self.request.GET.get("page")
        current_page = int(page) if page else 1

        start_index = int((current_page - 1) / page_numbers_range) * page_numbers_range
        end_index = start_index + page_numbers_range
        if end_index >= max_index:
            end_index = max_index
        page_range = paginator.page_range[start_index:end_index]
        context["page_range"] = page_range
        return context


class PersonDetail(DetailView):
    model = Person
    template_name = "people/person_detail.html"
    context_object_name = "person"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        kind = context["object"].kind
        if kind == Person.KIND_ACTOR:
            contents = Movie.objects.filter(cast=context["object"])
            content_kind = "movie"
        elif kind == Person.KIND_DIRECTOR:
            contents = Movie.objects.filter(director=context["object"])
            content_kind = "movie"
        elif kind == Person.KIND_WRITER:
            contents = Book.objects.filter(writer=context["object"])
            content_kind = "book"

        context["contents"] = contents
        context["content_kind"] = content_kind
        return context


class CreatePerson(user_mixins.LoggedInOnlyView, CreateView):
    model = Person
    fields = (
        "name",
        "photo",
        "kind",
    )


class UpdatePerson(user_mixins.LoggedInOnlyView, UpdateView):
    model = Person
    fields = ("name", "photo", "kind")

templates/mixins/add_review.html
<form action="{% url 'reviews:add' obj.pk %}?content_type={{type}}" method="POST" class="h-32 mb-3 flex items-center justify-between">
    {% csrf_token %}
    <div class="w-3/4 h-full flex flex-col">
        {% for field in form %}
            {{field}}
        {% endfor %}
    </div>
    <button class="bg-blue-400 hover:bg-blue-600 text-white font-bold rounded ml-4 w-1/4 h-full">Write</button>
</form>

templates/mixins/book.html
<div style="height: 70vh" class="rounded shadow-lg p-2">
  <a href="{% url 'books:book' book.pk %}">
    <div style="background-image:url({{book.cover_image.url}}); height: 60vh;" class="w-full bg-cover bg-center border border-gray-500 rounded-md"></div>
    <h3 class="text-gray-900 text-base mb-2 truncate block w-full">{{book.title}}</h3>
    <h5 class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">{{book.year}}</h5>
  </a>
</div>

templates/mixins/fav_button.html
{% load on_favs %}
{% on_favs obj as on_favs_boolean %}

<a class="ml-5 bg-blue-400 hover:bg-blue-600 text-white font-bold mt-4 py-2 px-4 rounded" href="{% url 'favs:add' obj.pk %}?kind={{kind}}">
{% if on_favs_boolean %}
  
    Remove from favs!
  
{% else %}
  
      Add to favs!
  
{% endif %}
  </a>

templates/mixins/form.html
<div class="flex justify-center mt-8">
<form method="POST" enctype="multipart/form-data" class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
    {% csrf_token %}
    
    {% for field in form %}
      <div class="mb-5">
          <label class="block text-gray-700 text-sm font-bold mb-2" for="{{field.auto_id}}">{{field.label}}</label>
          <div class="shadow appearance-none border rounded w-full  text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
          {{field}}
          </div>
      </div>
      <p>
        {% if field.errors %}
            <ul>
            {% for error in field.errors %}
                <li class="text-red-400">{{error}}</li> 
            {% endfor %}
            </ul>
        {% endif %}
      </p>
    {% endfor %}
    
    <button class="bg-blue-400 hover:bg-blue-600 text-white font-bold mt-2 py-2 px-4 rounded w-full">{{cta}}</button>
</form>
</div>

templates/mixins/movie.html
<div style="height: 70vh" class="rounded shadow-lg p-2">
  <a href="{% url 'movies:movie' movie.pk %}">
    <div style="background-image:url({{movie.cover_image.url}}); height: 60vh" class="w-full bg-cover bg-center border border-gray-500 rounded-md"></div>
    <h3 class="text-gray-900 text-base mb-2 truncate block w-full">{{movie.title}}</h3>
    <h5 class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">{{movie.year}}</h5>
  </a>
</div>

templates/mixins/person.html
<div style="height:70vh" class="rounded shadow-lg p-2">
  <a href="{% url 'people:person' person.pk %}">
    <div style="background-image:url({{person.photo.url}}); height: 60vh;" class="w-full bg-cover bg-center border border-gray-500 rounded-md"></div>
    <h3 class="text-gray-900 text-base mb-2 truncate block w-full">{{person.name}}</h3>
    <h5 class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">{{person.kind}}</h5>
  </a>
</div>

templates/mixins/show_review.html
<li class="mb-4 px-5">
  <div class="flex justify-between items-center">
    <h4 class="text-xl font-medium mb-1">{{review.created_by}} <span class="text-red-600 text-lg">♥︎{{review.rating}}</span></h4> 
    {% if review.created_by == user %}
      <a class="text-center bg-red-500 text-white w-4 h-5 text-sm -pt-1" href="{% url 'reviews:delete' review.pk %}?content_type={{type}}">X</a>
    {% endif %}
  </div>
  <p>{{review.text}}</p>
  <hr />
</li>