books/urls.py
from django.urls import path
from books.views import BooksView, BookDetail, CreateBook, UpdateBook

app_name = "books"

urlpatterns = [
    path("", BooksView.as_view(), name="books"),
    path("<int:pk>/", BookDetail.as_view(), name="book"),
    path("<int:pk>/update/", UpdateBook.as_view(), name="update"),
    path("create/", CreateBook.as_view(), name="create"),
]

categories/urls.py
from django.urls import path
from categories.views import CategoryDetail

app_name = "categories"

urlpatterns = [
    path("<int:pk>/", CategoryDetail.as_view(), name="category"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


def trigger_error(request):
    division_by_zero = 1 / 0


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("movies/", include("movies.urls", namespace="movies")),
    path("books/", include("books.urls", namespace="books")),
    path("categories/", include("categories.urls", namespace="categories")),
    path("people/", include("people.urls", namespace="people")),
    path("users/", include("users.urls", namespace="users")),
    path("favs/", include("favs.urls", namespace="favs")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("admin/", admin.site.urls),
    path("sentry-debug/", trigger_error),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from core.views import resolve_home, resolve_search

app_name = "core"

urlpatterns = [
    path("", resolve_home, name="home"),
    path("search/", resolve_search, name="search"),
]

people/urls.py
from django.urls import path
from people.views import PeopleView, PersonDetail, CreatePerson, UpdatePerson

app_name = "people"

urlpatterns = [
    path("", PeopleView.as_view(), name="people"),
    path("<int:pk>/", PersonDetail.as_view(), name="person"),
    path("<int:pk>/update/", UpdatePerson.as_view(), name="update"),
    path("create/", CreatePerson.as_view(), name="create"),
]

books/models.py
from django.urls import reverse
from django.db import models
from core.models import CoreModel


class Book(CoreModel):

    """ Book Model """

    title = models.CharField(max_length=120)
    year = models.IntegerField()
    cover_image = models.ImageField(upload_to="book_cover_images", blank=True)
    category = models.ForeignKey(
        "categories.Category", on_delete=models.CASCADE, related_name="books"
    )
    writer = models.ForeignKey(
        "people.Person", on_delete=models.CASCADE, related_name="books"
    )

    # field 대신 review의 평균값을 표시하기 위해 함수로 표현
    def rating(self):
        all_reviews = self.reviews.all()
        all_ratings = 0
        if len(all_reviews) > 0:
            for review in all_reviews:
                all_ratings += review.rating

            return round(all_ratings / len(all_reviews), 2)
        return 0

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("books:book", kwargs={"pk": self.pk})

    class Meta:
        ordering = ["-created_at"]

books/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.core.paginator import Paginator
from books.models import Book
from users import mixins as user_mixins
from reviews import forms as review_forms
from reviews import models as review_models


class BooksView(ListView):

    model = Book
    paginate_by = 15
    paginate_orphans = 5
    ordering = "-created_at"
    context_object_name = "books"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page_title"] = "All Books"

        paginator = context["paginator"]
        page_numbers_range = 10
        max_index = len(paginator.page_range)
        page = self.request.GET.get("page")
        current_page = int(page) if page else 1

        start_index = int((current_page - 1) / page_numbers_range) * page_numbers_range
        end_index = start_index + page_numbers_range
        if end_index >= max_index:
            end_index = max_index
        page_range = paginator.page_range[start_index:end_index]

        context["page_range"] = page_range
        return context


class BookDetail(DetailView):
    model = Book
    context_object_name = "book"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        review_form = review_forms.CreateReviewForm()
        context["form"] = review_form

        # book의 pk 가져옴
        book_pk = self.kwargs.get("pk")
        page = self.request.GET.get("page")

        # 한페이지당 표시 수랑 페이지 끊는 단위를 같이 쓰고 있음
        # 굳이 같이 쓸필요 없음
        page_numbers_range = 5
        # 가져온 book_pk에 해당하는 review만 가져옴
        review_list = review_models.Review.objects.filter(book__pk=book_pk)
        paginator = Paginator(review_list, page_numbers_range)
        max_index = len(paginator.page_range)
        reviews = paginator.get_page(page)

        # page 끊은 단위 계산
        current_page = int(page) if page else 1
        start_index = int((current_page - 1) / page_numbers_range) * page_numbers_range
        end_index = start_index + page_numbers_range
        if end_index >= max_index:
            end_index = max_index
        page_range = paginator.page_range[start_index:end_index]

        context["page_range"] = page_range
        context["reviews"] = reviews  # paginator  직접 반환
        # print(vars(reviews.paginator)) 안에 뭐 들었는지 확인용.
        return context


class CreateBook(user_mixins.LoggedInOnlyView, CreateView):
    model = Book
    fields = (
        "title",
        "year",
        "cover_image",
        "category",
        "writer",
    )


class UpdateBook(user_mixins.LoggedInOnlyView, UpdateView):
    model = Book
    fields = (
        "title",
        "year",
        "cover_image",
        "category",
        "writer",
    )

templates/books/book_detail.html
{% extends "base.html" %}

{% block page_title %}
  {{book.title}}
{% endblock page_title %}


{% block content %}

<div class="flex flex-col items-center bg-white shadow-md rounded px-8 pt-2 pb-8 mb-4">
  <h2 class="font-bold text-3xl mb-4">{{book.title}}</h2>
  <div style="background-image:url({{book.cover_image.url}}); height: 80vh;" class="w-1/4 bg-cover bg-center border border-gray-500 rounded-md mb-4"></div>
  <div class="flex items-center my-2">
    <div class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700">{{book.year}}</div>
    <div class="bg-orange-400 text-white px-3 shadow-md py-1 rounded-full mx-4 hover:bg-orange-600"><a href="{% url 'categories:category' book.category.pk %}">{{book.category}}</a></div>
    <div class="text-red-600">♥︎{{book.rating}}</div>
  </div>
  <div class="my-2">Writer:
    <div class="inline-block bg-white shadow-md rounded-full px-3 py-1 text-sm font-semibold text-gray-700 hover:bg-gray-300"><a href="{% url 'people:person' book.writer.pk %}">{{book.writer}}</a></div>
  </div>
  <div class="flex">
    <a class="bg-blue-400 hover:bg-blue-600 text-white font-bold mt-4 py-2 px-4 rounded" href="{% url 'books:update' book.pk %}">Edit Book</a>
    {% if user.is_authenticated %}
      {% include "mixins/fav_button.html" with obj=book kind='book' %}
    {% endif %}
  </div>

  <div class="container w-1/2">
    <hr class="my-5"/>
    <h3 class="text-center font-bold text-3xl text-white bg-blue-400 mb-4 rounded py-1">Review</h3>
    {% if user.is_authenticated %}
      {% include "mixins/add_review.html" with obj=book form=form type="book" %}
    {% endif %}
    <ul class="border rounded-md pt-2">
    {% for review in reviews %}
      {% include "mixins/show_review.html" with review=review type="book" %}
    {% endfor %}
      <div class="mt-2 flex justify-center mb-2">
        Page {{reviews.number}} of {{reviews.paginator.num_pages}} >>
        {% if reviews.has_previous %}
            <a class="bg-blue-400 hover:bg-blue-600 text-white font-bold py-1 px-2 rounded" href="?page={{reviews.previous_page_number}}">
                Previous
            </a>
        {% endif %}
        {% for page in page_range %}
          {% if page == reviews.number %}
              <span class="font-bold px-4">{{page}}</span>
          {% else %}
              <a class="hover:font-bold text-black px-4" href="?page={{page}}">{{page}}</a>
          {% endif %}
        {% endfor %}
        {% if reviews.has_next %}
            <a class="bg-blue-400 hover:bg-blue-600 text-white font-bold py-1 px-2 rounded" href="?page={{reviews.next_page_number}}">
                Next    
            </a>
        {% endif %}
      </div>
    </ul>
  </div>

</div>

{% endblock content %}

templates/books/book_form.html
{% extends "base.html" %}

{% block page_title %}
  Modify Book
{% endblock page_title %}

{% block content %}

  {% include 'mixins/form.html' with form=form cta="Save" %}

{% endblock content %}

templates/books/book_list.html
{% extends "base.html" %}

{% block page_title %}
  Books
{% endblock page_title %}

{% block content %}
<div class="px-5">
  <h2 class="ml-1 text-3xl text-blue-600">Books</h2>
  <div class="grid my-5 grid-cols-4 gap-10">
	{% for book in books %}
    {% include "mixins/book.html" with book=book %}
	{% endfor %}
  </div>
<hr />
</div>
  
<div class="mt-2 flex justify-center mb-2">
  Page {{page_obj.number}} of {{page_obj.paginator.num_pages}} >>
  {% if page_obj.has_previous %}
      <a class="bg-blue-400 hover:bg-blue-600 text-white font-bold py-1 px-2 rounded" href="?page={{page_obj.previous_page_number}}">
          Previous
      </a>
  {% endif %}
  {% for page in page_range %}
      {% if page == page_obj.number %}
          <span class="font-bold px-4">{{page}}</span>
      {% else %}
          <a class="hover:font-bold text-black px-4" href="?page={{page}}">{{page}}</a>
      {% endif %}
  {% endfor %}
  {% if page_obj.has_next %}
      <a class="bg-blue-400 hover:bg-blue-600 text-white font-bold py-1 px-2 rounded" href="?page={{page_obj.next_page_number}}">
          Next    
      </a>
  {% endif %}
</div>
{% endblock content %}